CREATE TABLE tags (
  id SERIAL UNIQUE,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);

ALTER TABLE tags ADD CONSTRAINT PK_tags_id
	PRIMARY KEY (id)
;

ALTER TABLE tags ADD CONSTRAINT UQ_tags_name UNIQUE (name)
;

ALTER TABLE tags ADD CONSTRAINT CHK_tags_text_not_empty
  CHECK (btrim(name) <> '')
;
