DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS languages CASCADE;
DROP TABLE IF EXISTS colors CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS card_tags CASCADE;
DROP TABLE IF EXISTS card_votes CASCADE;
